# Generated by Django 4.1.7 on 2023-02-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=20)),
                ('bio', models.TextField(default='Unknown')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
